### PR TITLE
Resource Page and Guide Updates

### PR DESCRIPTION
**Pull request by amitafr**
Update landing page feature text
Add Resources to harp
Style Internal Resources page
Implement relevant guide markdown 

To Do: Update the guides to have a cohesive header and footer to the rest of the website

### CODE REVIEW

**Comment by amitafr** [comment]
@ericjim sorry the changes are not separated to smaller chucks
Could you have a look please

**Comment by ericjim** [comment]
@amitafr could you attach screenshots of the changes?

**Comment by amitafr** [comment]
@ericjim 

augury_changes
guides
resouces
footer

**Comment by ericjim** [comment]
Wow, so pretty.

**Comment by ericjim** [comment]
@amitafr  LGTM. We don't deploy until the todo has been taken care of.

**Pull request merged**
